### ISSUE TITLE
Using CameraIntentHelper With Fragment

### ISSUE THREAD

**Issue by jagatappv** [ralfgehrer/AndroidCameraUtil#11]
Hey,

I am using this library.

Its working fine. I have integrated in my activity.

Now i want to use this library in fragment.

Can you help me, how can i use with this library within fragment?

Thanks

**Comment by RayTW** [comment]
in Fragment, you can:
Activity activity = getActivity();
		if (activity != null) {
			Intent intent = new Intent().setClass(activity,
					yourCamaraActivity.class);
			startActivity(intent);
			activity.finish();
		}

**Comment by ralfgehrer** [comment]
I refactored the code and included a Fragment sample implementation. Check out the CameraIntentFragment held by the ParentActivity.
